"""
Data Quality Framework for Legacy CDW -> Modern Delta Lake Migration.

Runs post-ingestion validation checks and generates a markdown report.

Checks:
  1. Row count reconciliation (source vs target)
  2. Null checks on required fields
  3. Referential integrity between loan_accounts and borrowers/products
  4. Referential integrity between payments and loan_accounts
  5. Business rule validations (balance > 0 for active, closed date for closed, etc.)

Usage:
    spark-submit --master local[*] data_quality_checks.py \
        --source-dir /mnt/legacy \
        --source-format csv \
        --target-db loan_warehouse \
        --report-path /mnt/migration/DATA_QUALITY_REPORT.md
"""

import argparse
import logging
from dataclasses import dataclass, field
from datetime import datetime

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("data_quality")


@dataclass
class CheckResult:
    category: str
    check_name: str
    passed: bool
    detail: str
    severity: str = "ERROR"


@dataclass
class QualityReport:
    results: list[CheckResult] = field(default_factory=list)
    started_at: str = ""
    finished_at: str = ""

    def add(self, result: CheckResult) -> None:
        self.results.append(result)
        status = "PASS" if result.passed else "FAIL"
        logger.info("[%s] %s / %s: %s", status, result.category, result.check_name, result.detail)

    @property
    def total(self) -> int:
        return len(self.results)

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed(self) -> int:
        return sum(1 for r in self.results if not r.passed)

    def to_markdown(self) -> str:
        lines = [
            "# Data Quality Report",
            "",
            f"**Run started:** {self.started_at}",
            f"**Run finished:** {self.finished_at}",
            "",
            "## Summary",
            "",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total checks | {self.total} |",
            f"| Passed | {self.passed} |",
            f"| Failed | {self.failed} |",
            f"| Pass rate | {self.passed / self.total * 100:.1f}% |" if self.total > 0 else "",
            "",
            "## Detailed Results",
            "",
            "| Category | Check | Result | Severity | Detail |",
            "|----------|-------|--------|----------|--------|",
        ]
        for r in self.results:
            status = "PASS" if r.passed else "**FAIL**"
            lines.append(
                f"| {r.category} | {r.check_name} | {status} | {r.severity} | {r.detail} |"
            )

        # Failed checks summary
        failed = [r for r in self.results if not r.passed]
        if failed:
            lines += [
                "",
                "## Failed Checks Detail",
                "",
            ]
            for r in failed:
                lines.append(f"- **[{r.severity}] {r.category} / {r.check_name}**: {r.detail}")

        lines += [
            "",
            "---",
            f"*Generated by data_quality_checks.py on {self.finished_at}*",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 1. Row count reconciliation
# ---------------------------------------------------------------------------

def check_row_counts(
    spark: SparkSession,
    source_dir: str,
    source_format: str,
    target_db: str,
    report: QualityReport,
) -> None:
    """Compare row counts between legacy source files and modern target tables."""
    table_map = {
        "cdw_borr_mstr": "borrowers",
        "cdw_ln_prod": "loan_products",
        "cdw_ln_acct": "loan_accounts",
        "cdw_pmt_hist": "payments",
    }

    for source_name, target_name in table_map.items():
        source_path = f"{source_dir}/{source_name}"
        target_table = f"{target_db}.{target_name}"

        try:
            source_df = spark.read.option("header", "true").format(source_format).load(source_path)
            source_count = source_df.count()
        except Exception as e:
            report.add(CheckResult(
                category="Row Count",
                check_name=f"{source_name} source readable",
                passed=False,
                detail=f"Cannot read source: {e}",
            ))
            continue

        try:
            target_df = spark.table(target_table)
            target_count = target_df.count()
        except Exception as e:
            report.add(CheckResult(
                category="Row Count",
                check_name=f"{target_name} target readable",
                passed=False,
                detail=f"Cannot read target: {e}",
            ))
            continue

        match = source_count == target_count
        report.add(CheckResult(
            category="Row Count",
            check_name=f"{source_name} -> {target_name}",
            passed=match,
            detail=f"Source={source_count}, Target={target_count}",
        ))


# ---------------------------------------------------------------------------
# 2. Null checks on required fields
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = {
    "borrowers": ["external_id", "first_name", "last_name"],
    "loan_products": ["code", "name", "type", "term_months", "rate_type"],
    "loan_accounts": [
        "account_number", "borrower_id", "product_id",
        "original_amount", "current_balance", "interest_rate",
        "term_months", "monthly_payment", "origination_date", "maturity_date",
    ],
    "payments": [
        "loan_account_id", "payment_date", "total_amount", "type", "status",
    ],
}


def check_nulls(
    spark: SparkSession,
    target_db: str,
    report: QualityReport,
) -> None:
    """Check that required fields have no NULLs in target tables."""
    for table_name, columns in REQUIRED_FIELDS.items():
        target_table = f"{target_db}.{table_name}"
        try:
            df = spark.table(target_table)
        except Exception:
            report.add(CheckResult(
                category="Null Check",
                check_name=f"{table_name} table exists",
                passed=False,
                detail=f"Table {target_table} not found",
            ))
            continue

        total_rows = df.count()
        for col_name in columns:
            if col_name not in df.columns:
                report.add(CheckResult(
                    category="Null Check",
                    check_name=f"{table_name}.{col_name}",
                    passed=False,
                    detail=f"Column {col_name} not found in {table_name}",
                ))
                continue

            null_count = df.filter(F.col(col_name).isNull()).count()
            passed = null_count == 0
            report.add(CheckResult(
                category="Null Check",
                check_name=f"{table_name}.{col_name} NOT NULL",
                passed=passed,
                detail=f"{null_count}/{total_rows} nulls",
                severity="ERROR" if not passed else "INFO",
            ))


# ---------------------------------------------------------------------------
# 3. Referential integrity
# ---------------------------------------------------------------------------

def check_referential_integrity(
    spark: SparkSession,
    target_db: str,
    report: QualityReport,
) -> None:
    """Check FK relationships between target tables."""
    checks = [
        {
            "name": "loan_accounts.borrower_id -> borrowers",
            "child_table": "loan_accounts",
            "child_col": "borrower_id",
            "parent_table": "borrowers",
            "parent_col": "borrower_id",
        },
        {
            "name": "loan_accounts.product_id -> loan_products",
            "child_table": "loan_accounts",
            "child_col": "product_id",
            "parent_table": "loan_products",
            "parent_col": "product_id",
        },
        {
            "name": "payments.loan_account_id -> loan_accounts",
            "child_table": "payments",
            "child_col": "loan_account_id",
            "parent_table": "loan_accounts",
            "parent_col": "loan_account_id",
        },
    ]

    for check in checks:
        try:
            child_df = spark.table(f"{target_db}.{check['child_table']}")
            parent_df = spark.table(f"{target_db}.{check['parent_table']}")

            # Find orphan rows: child FK values not in parent PK
            child_keys = child_df.select(
                F.col(check["child_col"]).alias("_fk")
            ).distinct()
            parent_keys = parent_df.select(
                F.col(check["parent_col"]).alias("_pk")
            ).distinct()

            orphans = child_keys.join(parent_keys, child_keys["_fk"] == parent_keys["_pk"], "left_anti")
            orphan_count = orphans.count()

            passed = orphan_count == 0
            report.add(CheckResult(
                category="Referential Integrity",
                check_name=check["name"],
                passed=passed,
                detail=f"{orphan_count} orphan rows",
            ))
        except Exception as e:
            report.add(CheckResult(
                category="Referential Integrity",
                check_name=check["name"],
                passed=False,
                detail=f"Error: {e}",
            ))


# ---------------------------------------------------------------------------
# 4. Business rule validations
# ---------------------------------------------------------------------------

def check_business_rules(
    spark: SparkSession,
    target_db: str,
    report: QualityReport,
) -> None:
    """Validate domain-specific business rules."""

    # --- Loan accounts rules ---
    try:
        loans_df = spark.table(f"{target_db}.loan_accounts")

        # Rule: Active loans must have current_balance > 0
        active_zero_balance = loans_df.filter(
            (F.col("status") == "Active") & (F.col("current_balance") <= 0)
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Active loans have balance > 0",
            passed=active_zero_balance == 0,
            detail=f"{active_zero_balance} active loans with balance <= 0",
            severity="WARNING",
        ))

        # Rule: Closed loans should have maturity_date <= today (or they shouldn't be closed)
        # This is a soft check since loans can be closed early
        closed_loans = loans_df.filter(F.col("status") == "Closed")
        closed_count = closed_loans.count()
        if closed_count > 0:
            closed_no_maturity = closed_loans.filter(
                F.col("maturity_date").isNull()
            ).count()
            report.add(CheckResult(
                category="Business Rule",
                check_name="Closed loans have maturity_date",
                passed=closed_no_maturity == 0,
                detail=f"{closed_no_maturity}/{closed_count} closed loans missing maturity_date",
                severity="WARNING",
            ))
        else:
            report.add(CheckResult(
                category="Business Rule",
                check_name="Closed loans have maturity_date",
                passed=True,
                detail="No closed loans in dataset (check skipped)",
                severity="INFO",
            ))

        # Rule: Delinquency days should be >= 0
        negative_dlq = loans_df.filter(F.col("delinquency_days") < 0).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Delinquency days >= 0",
            passed=negative_dlq == 0,
            detail=f"{negative_dlq} loans with negative delinquency days",
        ))

        # Rule: LTV percent should be between 0 and 200 (reasonable range)
        bad_ltv = loans_df.filter(
            (F.col("ltv_percent").isNotNull())
            & ((F.col("ltv_percent") < 0) | (F.col("ltv_percent") > 200))
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="LTV percent in valid range (0-200)",
            passed=bad_ltv == 0,
            detail=f"{bad_ltv} loans with out-of-range LTV",
            severity="WARNING",
        ))

        # Rule: origination_date should be before maturity_date
        bad_dates = loans_df.filter(
            F.col("origination_date") >= F.col("maturity_date")
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Origination date < maturity date",
            passed=bad_dates == 0,
            detail=f"{bad_dates} loans with origination >= maturity",
        ))

        # Rule: interest rate should be positive and reasonable (0-30%)
        bad_rates = loans_df.filter(
            (F.col("interest_rate") <= 0) | (F.col("interest_rate") > 30)
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Interest rate in valid range (0-30%)",
            passed=bad_rates == 0,
            detail=f"{bad_rates} loans with out-of-range interest rate",
            severity="WARNING",
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rule",
            check_name="Loan accounts accessible",
            passed=False,
            detail=f"Error accessing loan_accounts: {e}",
        ))

    # --- Payment rules ---
    try:
        payments_df = spark.table(f"{target_db}.payments")

        # Rule: total_amount should be > 0
        zero_payments = payments_df.filter(F.col("total_amount") <= 0).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Payment amounts > 0",
            passed=zero_payments == 0,
            detail=f"{zero_payments} payments with amount <= 0",
            severity="WARNING",
        ))

        # Rule: principal + interest + escrow + late_fee should approximately equal total
        payments_with_sum = payments_df.withColumn(
            "_component_sum",
            F.coalesce(F.col("principal_amount"), F.lit(0))
            + F.coalesce(F.col("interest_amount"), F.lit(0))
            + F.coalesce(F.col("escrow_amount"), F.lit(0))
            + F.coalesce(F.col("late_fee"), F.lit(0)),
        )
        mismatched = payments_with_sum.filter(
            F.abs(F.col("_component_sum") - F.col("total_amount")) > 0.02
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Payment component sum matches total",
            passed=mismatched == 0,
            detail=f"{mismatched} payments where components do not sum to total (tolerance=0.02)",
            severity="WARNING",
        ))

        # Rule: received_date should be on or before processed_date
        bad_recv = payments_df.filter(
            (F.col("received_date").isNotNull())
            & (F.col("processed_date").isNotNull())
            & (F.col("received_date") > F.col("processed_date"))
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="received_date <= processed_date",
            passed=bad_recv == 0,
            detail=f"{bad_recv} payments where received > processed",
            severity="WARNING",
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rule",
            check_name="Payments accessible",
            passed=False,
            detail=f"Error accessing payments: {e}",
        ))

    # --- Borrower rules ---
    try:
        borrowers_df = spark.table(f"{target_db}.borrowers")

        # Rule: credit score should be in valid range (300-850)
        bad_credit = borrowers_df.filter(
            (F.col("credit_score").isNotNull())
            & ((F.col("credit_score") < 300) | (F.col("credit_score") > 850))
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Credit score in valid range (300-850)",
            passed=bad_credit == 0,
            detail=f"{bad_credit} borrowers with out-of-range credit score",
            severity="WARNING",
        ))

        # Rule: annual income should be >= 0
        neg_income = borrowers_df.filter(
            (F.col("annual_income").isNotNull()) & (F.col("annual_income") < 0)
        ).count()
        report.add(CheckResult(
            category="Business Rule",
            check_name="Annual income >= 0",
            passed=neg_income == 0,
            detail=f"{neg_income} borrowers with negative income",
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rule",
            check_name="Borrowers accessible",
            passed=False,
            detail=f"Error accessing borrowers: {e}",
        ))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_all_checks(
    spark: SparkSession,
    source_dir: str,
    source_format: str,
    target_db: str,
) -> QualityReport:
    report = QualityReport(started_at=datetime.utcnow().isoformat())

    logger.info("=" * 60)
    logger.info("DATA QUALITY CHECKS")
    logger.info("=" * 60)

    logger.info("--- Row Count Reconciliation ---")
    check_row_counts(spark, source_dir, source_format, target_db, report)

    logger.info("--- Null Checks ---")
    check_nulls(spark, target_db, report)

    logger.info("--- Referential Integrity ---")
    check_referential_integrity(spark, target_db, report)

    logger.info("--- Business Rules ---")
    check_business_rules(spark, target_db, report)

    report.finished_at = datetime.utcnow().isoformat()

    logger.info("=" * 60)
    logger.info("QUALITY CHECK SUMMARY: %d/%d passed", report.passed, report.total)
    logger.info("=" * 60)

    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Run data quality checks post-migration")
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--source-format", default="csv", choices=["csv", "parquet"])
    parser.add_argument("--target-db", default="loan_warehouse")
    parser.add_argument("--report-path", default="/mnt/migration/DATA_QUALITY_REPORT.md")
    opts = parser.parse_args()

    spark = SparkSession.builder.appName("DataQualityChecks").getOrCreate()

    report = run_all_checks(spark, opts.source_dir, opts.source_format, opts.target_db)

    # Write markdown report
    md_content = report.to_markdown()

    # Write via Spark to support DBFS paths
    spark.sparkContext.parallelize([md_content]).coalesce(1).saveAsTextFile(
        opts.report_path + "_raw"
    )
    logger.info("Quality report written to %s_raw", opts.report_path)

    # Also write locally if possible
    try:
        with open(opts.report_path, "w") as f:
            f.write(md_content)
        logger.info("Quality report also written locally to %s", opts.report_path)
    except Exception:
        logger.info("Could not write local file (expected in DBFS-only environments)")

    if report.failed > 0:
        logger.warning(
            "DATA QUALITY: %d checks FAILED out of %d total",
            report.failed,
            report.total,
        )
    else:
        logger.info("DATA QUALITY: ALL %d checks PASSED", report.total)

    spark.stop()


if __name__ == "__main__":
    main()
