"""Generate DATA_QUALITY_REPORT.md from quality check results.

Usage (Databricks notebook or job):
    from quality.generate_report import run_quality_checks
    run_quality_checks(spark, source_counts)
"""

import logging
import os
from datetime import datetime

from pyspark.sql import SparkSession

from data_quality_checks import (
    QualityReport,
    check_business_rules,
    check_nulls,
    check_referential_integrity,
    check_row_counts,
)

logger = logging.getLogger("quality.report")
logging.basicConfig(level=logging.INFO)

REPORT_PATH = "DATA_QUALITY_REPORT.md"


def run_quality_checks(
    spark: SparkSession,
    source_counts: dict,
    report_path: str = REPORT_PATH,
) -> QualityReport:
    """Execute all quality checks and write the markdown report."""
    report = QualityReport()

    logger.info("Running row count reconciliation checks")
    check_row_counts(spark, report, source_counts)

    logger.info("Running null checks on required fields")
    check_nulls(spark, report)

    logger.info("Running referential integrity checks")
    check_referential_integrity(spark, report)

    logger.info("Running business rule validation checks")
    check_business_rules(spark, report)

    md = _render_markdown(report)
    _write_report(md, report_path)

    logger.info(
        "Quality report: %d passed, %d failed, %d warnings — written to %s",
        report.passed,
        report.failed,
        report.warnings,
        report_path,
    )
    return report


def _render_markdown(report: QualityReport) -> str:
    """Render the QualityReport into a markdown string."""
    lines = [
        "# Data Quality Report",
        "",
        f"**Generated:** {report.run_timestamp} UTC",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Checks | {len(report.results)} |",
        f"| Passed | {report.passed} |",
        f"| Failed | {report.failed} |",
        f"| Warnings | {report.warnings} |",
        "",
        f"**Overall Status:** {'PASS' if report.failed == 0 else 'FAIL'}",
        "",
    ]

    # Group results by category
    categories = {}
    for r in report.results:
        categories.setdefault(r.category, []).append(r)

    for category, results in categories.items():
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Check | Table | Status | Detail |")
        lines.append("|-------|-------|--------|--------|")
        for r in results:
            status_icon = {"PASS": "PASS", "FAIL": "**FAIL**", "WARN": "WARN"}[r.status]
            table_short = r.table.split(".")[-1] if "." in r.table else r.table
            lines.append(f"| {r.check_name} | {table_short} | {status_icon} | {r.detail} |")
        lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by the loan migration data quality framework.*")
    lines.append("")

    return "\n".join(lines)


def _write_report(content: str, path: str) -> None:
    """Write the report to local filesystem (or DBFS if running on Databricks)."""
    # Try DBFS first, fall back to local
    try:
        dbfs_path = f"/dbfs/{path}" if not path.startswith("/dbfs") else path
        with open(dbfs_path, "w") as f:
            f.write(content)
        logger.info("Report written to DBFS: %s", dbfs_path)
    except (OSError, IOError):
        with open(path, "w") as f:
            f.write(content)
        logger.info("Report written locally: %s", os.path.abspath(path))


if __name__ == "__main__":
    spark = SparkSession.builder.appName("DataQuality_Report").getOrCreate()
    # When running standalone, you must supply source counts from the ingestion run
    example_counts = {
        "cdw_borr_mstr": 0,
        "cdw_ln_prod": 0,
        "cdw_ln_acct": 0,
        "cdw_pmt_hist": 0,
    }
    logger.warning(
        "Running with zero source counts. Pass actual counts from the ingestion pipeline."
    )
    run_quality_checks(spark, example_counts)
