"""
Generate DATA_QUALITY_REPORT.md from quality check results.

Usage:
    from databricks.quality.data_quality_checks import run_all_checks
    from databricks.quality.generate_report import generate_report

    report = run_all_checks(spark, source_counts)
    generate_report(report, output_path="/dbfs/reports/DATA_QUALITY_REPORT.md")
"""

import datetime
from databricks.quality.data_quality_checks import QualityReport, CheckResult
import logging

logger = logging.getLogger("dq_report")


def generate_report(report: QualityReport, output_path: str = "DATA_QUALITY_REPORT.md") -> str:
    """Generate a Markdown data quality report.

    Args:
        report: QualityReport from run_all_checks.
        output_path: File path to write the report. Defaults to current directory.

    Returns:
        The Markdown content as a string.
    """
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    overall_status = "PASS" if report.failed == 0 else "FAIL"

    lines = []
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append(f"**Generated:** {now}")
    lines.append(f"**Overall Status:** {overall_status}")
    lines.append(f"**Total Checks:** {report.total} | **Passed:** {report.passed} | **Failed:** {report.failed}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Group results by category
    categories = {}
    for r in report.results:
        categories.setdefault(r.category, []).append(r)

    for cat_name, results in categories.items():
        cat_pass = sum(1 for r in results if r.passed)
        cat_fail = sum(1 for r in results if not r.passed)
        cat_status = "PASS" if cat_fail == 0 else "FAIL"

        lines.append(f"## {cat_name} ({cat_status})")
        lines.append("")
        lines.append(f"**{cat_pass} passed, {cat_fail} failed** out of {len(results)} checks")
        lines.append("")
        lines.append("| Status | Table | Check | Detail | Expected | Actual |")
        lines.append("|--------|-------|-------|--------|----------|--------|")

        for r in results:
            status_icon = "PASS" if r.passed else "**FAIL**"
            short_table = r.table.replace("loan_warehouse.", "")
            lines.append(
                f"| {status_icon} | {short_table} | {r.check_name} | {r.detail} | {r.expected} | {r.actual} |"
            )

        lines.append("")

    # Summary of failures
    failures = [r for r in report.results if not r.passed]
    if failures:
        lines.append("## Failed Checks Summary")
        lines.append("")
        lines.append("The following checks require attention before the migration can be signed off:")
        lines.append("")
        for i, f in enumerate(failures, 1):
            short_table = f.table.replace("loan_warehouse.", "")
            lines.append(f"{i}. **{short_table} / {f.check_name}**: {f.detail}")
        lines.append("")
    else:
        lines.append("## All Checks Passed")
        lines.append("")
        lines.append("All data quality checks passed. The migration data is consistent and ready for production use.")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by the CDW Migration Data Quality Framework.*")

    content = "\n".join(lines)

    with open(output_path, "w") as fh:
        fh.write(content)
    logger.info("Data quality report written to %s", output_path)

    return content


def run_and_report(spark, source_counts: dict = None,
                   output_path: str = "DATA_QUALITY_REPORT.md") -> QualityReport:
    """Convenience function: run all checks and generate report in one call.

    Args:
        spark: Active SparkSession.
        source_counts: Optional row count expectations.
        output_path: Report output path.

    Returns:
        QualityReport instance.
    """
    from databricks.quality.data_quality_checks import run_all_checks

    report = run_all_checks(spark, source_counts)
    generate_report(report, output_path)
    return report
