"""
Generate a DATA_QUALITY_REPORT.md from the results of data_quality_checks.py.

Reads the JSON output from the quality checks and produces a human-readable
Markdown report with pass/fail tables grouped by category.

Usage:
    python generate_report.py \
        --input /tmp/dq_results.json \
        --output /Workspace/reports/DATA_QUALITY_REPORT.md

Or invoke programmatically from a Databricks notebook:
    from generate_report import generate_report
    generate_report(check_results, "/dbfs/reports/DATA_QUALITY_REPORT.md")
"""

import argparse
import json
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class CheckResult:
    category: str
    table: str
    check_name: str
    passed: bool
    detail: str
    expected: Optional[str] = None
    actual: Optional[str] = None


CATEGORY_LABELS = {
    "reconciliation": "Row Count Reconciliation",
    "null_check": "Null Checks on Required Fields",
    "referential": "Referential Integrity",
    "business_rule": "Business Rule Validation",
}

CATEGORY_ORDER = ["reconciliation", "null_check", "referential", "business_rule"]


def generate_report(results: List[CheckResult], output_path: str) -> str:
    """Generate the Markdown report and write it to ``output_path``.

    Returns the Markdown content as a string.
    """

    total = len(results)
    passed = sum(1 for r in results if r.passed)
    failed = total - passed
    run_ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Group results by category
    by_category = defaultdict(list)
    for r in results:
        by_category[r.category].append(r)

    lines = []
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append(f"**Generated:** {run_ts}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Checks | {total} |")
    lines.append(f"| Passed | {passed} |")
    lines.append(f"| Failed | {failed} |")
    lines.append(f"| Pass Rate | {passed/total*100:.1f}% |" if total > 0 else "| Pass Rate | N/A |")
    lines.append("")

    overall_status = "ALL CHECKS PASSED" if failed == 0 else f"{failed} CHECK(S) FAILED"
    lines.append(f"**Overall Status:** {overall_status}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for cat_key in CATEGORY_ORDER:
        if cat_key not in by_category:
            continue
        cat_results = by_category[cat_key]
        cat_label = CATEGORY_LABELS.get(cat_key, cat_key)
        cat_passed = sum(1 for r in cat_results if r.passed)
        cat_total = len(cat_results)

        lines.append(f"## {cat_label}")
        lines.append("")
        lines.append(f"**{cat_passed}/{cat_total} passed**")
        lines.append("")
        lines.append("| Status | Table | Check | Detail | Expected | Actual |")
        lines.append("|--------|-------|-------|--------|----------|--------|")

        for r in cat_results:
            status = "PASS" if r.passed else "**FAIL**"
            expected = r.expected or "—"
            actual = r.actual or "—"
            lines.append(
                f"| {status} | `{r.table}` | `{r.check_name}` "
                f"| {r.detail} | {expected} | {actual} |"
            )

        lines.append("")

    # Failed checks detail section
    failed_results = [r for r in results if not r.passed]
    if failed_results:
        lines.append("---")
        lines.append("")
        lines.append("## Failed Checks — Action Items")
        lines.append("")
        for i, r in enumerate(failed_results, 1):
            lines.append(f"### {i}. `{r.table}` — `{r.check_name}`")
            lines.append("")
            lines.append(f"- **Category:** {CATEGORY_LABELS.get(r.category, r.category)}")
            lines.append(f"- **Detail:** {r.detail}")
            if r.expected:
                lines.append(f"- **Expected:** {r.expected}")
            if r.actual:
                lines.append(f"- **Actual:** {r.actual}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by the CDW Migration Data Quality Framework.*")
    lines.append("")

    content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Report written to {output_path}")
    return content


def load_results_from_json(json_path: str) -> List[CheckResult]:
    """Load CheckResult objects from a JSON file."""
    with open(json_path) as f:
        data = json.load(f)
    return [CheckResult(**item) for item in data]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate data quality report")
    parser.add_argument("--input", default="/tmp/dq_results.json")
    parser.add_argument("--output", default="/Workspace/reports/DATA_QUALITY_REPORT.md")
    args = parser.parse_args()

    results = load_results_from_json(args.input)
    generate_report(results, args.output)
