"""
Data quality validation framework for the CDW -> Delta Lake migration.

Runs post-ingestion checks and produces a structured report:
  1. Row count reconciliation (source vs target)
  2. Null checks on required fields
  3. Referential integrity between loan_accounts <-> borrowers / loan_products,
     and payments <-> loan_accounts
  4. Business rule validation (loan balance > 0 for active loans, etc.)

Usage:
    from quality.validators import run_all_checks
    report = run_all_checks(spark, source_counts={...})
    report.write_markdown("dbfs:/mnt/reports/DATA_QUALITY_REPORT.md")
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F


@dataclass
class CheckResult:
    """Single data quality check result."""
    category: str
    check_name: str
    table: str
    passed: bool
    detail: str
    expected: Optional[str] = None
    actual: Optional[str] = None


@dataclass
class QualityReport:
    """Aggregated data quality report."""
    results: list = field(default_factory=list)
    generated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")

    def add(self, result: CheckResult) -> None:
        self.results.append(result)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)

    @property
    def total_count(self) -> int:
        return len(self.results)

    @property
    def all_passed(self) -> bool:
        return self.failed_count == 0

    def write_markdown(self, path: str, spark: SparkSession) -> str:
        """Generate DATA_QUALITY_REPORT.md content and write to DBFS."""
        lines = []
        lines.append("# Data Quality Report")
        lines.append("")
        lines.append(f"**Generated:** {self.generated_at}")
        lines.append(f"**Overall Status:** {'PASS' if self.all_passed else 'FAIL'}")
        lines.append(f"**Checks Passed:** {self.passed_count} / {self.total_count}")
        lines.append("")

        categories = sorted(set(r.category for r in self.results))
        for cat in categories:
            lines.append(f"## {cat}")
            lines.append("")
            lines.append("| Check | Table | Status | Detail |")
            lines.append("|-------|-------|--------|--------|")
            for r in self.results:
                if r.category != cat:
                    continue
                status = "PASS" if r.passed else "**FAIL**"
                detail_parts = [r.detail]
                if r.expected is not None:
                    detail_parts.append(f"Expected: {r.expected}")
                if r.actual is not None:
                    detail_parts.append(f"Actual: {r.actual}")
                detail_str = "; ".join(detail_parts)
                lines.append(f"| {r.check_name} | {r.table} | {status} | {detail_str} |")
            lines.append("")

        if self.failed_count > 0:
            lines.append("## Failed Checks Summary")
            lines.append("")
            for r in self.results:
                if not r.passed:
                    lines.append(f"- **[{r.category}] {r.check_name}** ({r.table}): {r.detail}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Report generated by CDW Migration Data Quality Framework*")

        content = "\n".join(lines)

        # Write to DBFS using Spark
        rdd = spark.sparkContext.parallelize([content])
        rdd.coalesce(1).saveAsTextFile(path)

        return content


# ---------------------------------------------------------------------------
# 1. Row Count Reconciliation
# ---------------------------------------------------------------------------

def check_row_counts(
    spark: SparkSession,
    report: QualityReport,
    source_counts: dict,
) -> None:
    """
    Compare source row counts against target Delta tables.

    source_counts: dict mapping table name -> expected count, e.g.:
        {"borrowers": 5, "loan_products": 5, "loan_accounts": 5, "payments": 10}
    """
    table_map = {
        "borrowers": "loan_warehouse.borrowers",
        "loan_products": "loan_warehouse.loan_products",
        "loan_accounts": "loan_warehouse.loan_accounts",
        "payments": "loan_warehouse.payments",
    }

    for short_name, full_table in table_map.items():
        expected = source_counts.get(short_name)
        if expected is None:
            continue

        try:
            actual = spark.table(full_table).count()
            passed = actual == expected
            report.add(CheckResult(
                category="Row Count Reconciliation",
                check_name=f"row_count_{short_name}",
                table=short_name,
                passed=passed,
                detail=f"Source={expected}, Target={actual}",
                expected=str(expected),
                actual=str(actual),
            ))
        except Exception as e:
            report.add(CheckResult(
                category="Row Count Reconciliation",
                check_name=f"row_count_{short_name}",
                table=short_name,
                passed=False,
                detail=f"Error reading table: {e}",
            ))


# ---------------------------------------------------------------------------
# 2. Null Checks on Required Fields
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = {
    "borrowers": ["external_id", "first_name", "last_name", "status"],
    "loan_products": ["code", "name", "type", "term_months", "rate_type"],
    "loan_accounts": [
        "account_number", "borrower_key", "product_key",
        "original_amount", "current_balance", "interest_rate",
        "term_months", "monthly_payment", "origination_date", "maturity_date", "status",
    ],
    "payments": [
        "legacy_sequence_nbr", "loan_key", "payment_date",
        "total_amount", "type", "status",
    ],
}


def check_nulls(
    spark: SparkSession,
    report: QualityReport,
) -> None:
    """Check that required columns have no null values."""
    table_map = {
        "borrowers": "loan_warehouse.borrowers",
        "loan_products": "loan_warehouse.loan_products",
        "loan_accounts": "loan_warehouse.loan_accounts",
        "payments": "loan_warehouse.payments",
    }

    for short_name, full_table in table_map.items():
        required = REQUIRED_FIELDS.get(short_name, [])
        try:
            df = spark.table(full_table)
            for col_name in required:
                null_count = df.filter(F.col(col_name).isNull()).count()
                passed = null_count == 0
                report.add(CheckResult(
                    category="Null Checks",
                    check_name=f"not_null_{col_name}",
                    table=short_name,
                    passed=passed,
                    detail=f"{null_count} null(s) found" if not passed else "No nulls",
                    expected="0",
                    actual=str(null_count),
                ))
        except Exception as e:
            report.add(CheckResult(
                category="Null Checks",
                check_name=f"null_check_{short_name}",
                table=short_name,
                passed=False,
                detail=f"Error: {e}",
            ))


# ---------------------------------------------------------------------------
# 3. Referential Integrity
# ---------------------------------------------------------------------------

def check_referential_integrity(
    spark: SparkSession,
    report: QualityReport,
) -> None:
    """Verify FK relationships between tables."""

    # loan_accounts.borrower_key -> borrowers.borrower_key
    try:
        loans = spark.table("loan_warehouse.loan_accounts")
        borrowers = spark.table("loan_warehouse.borrowers")
        orphan_borrower = loans.join(
            borrowers,
            loans["borrower_key"] == borrowers["borrower_key"],
            "left_anti",
        ).count()
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="loan_accounts_borrower_fk",
            table="loan_accounts -> borrowers",
            passed=orphan_borrower == 0,
            detail=f"{orphan_borrower} loan(s) with no matching borrower",
            expected="0",
            actual=str(orphan_borrower),
        ))
    except Exception as e:
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="loan_accounts_borrower_fk",
            table="loan_accounts -> borrowers",
            passed=False,
            detail=f"Error: {e}",
        ))

    # loan_accounts.product_key -> loan_products.product_key
    try:
        loans = spark.table("loan_warehouse.loan_accounts")
        products = spark.table("loan_warehouse.loan_products")
        orphan_product = loans.join(
            products,
            loans["product_key"] == products["product_key"],
            "left_anti",
        ).count()
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="loan_accounts_product_fk",
            table="loan_accounts -> loan_products",
            passed=orphan_product == 0,
            detail=f"{orphan_product} loan(s) with no matching product",
            expected="0",
            actual=str(orphan_product),
        ))
    except Exception as e:
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="loan_accounts_product_fk",
            table="loan_accounts -> loan_products",
            passed=False,
            detail=f"Error: {e}",
        ))

    # payments.loan_key -> loan_accounts.loan_key
    try:
        payments = spark.table("loan_warehouse.payments")
        loans = spark.table("loan_warehouse.loan_accounts")
        orphan_loan = payments.join(
            loans,
            payments["loan_key"] == loans["loan_key"],
            "left_anti",
        ).count()
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="payments_loan_fk",
            table="payments -> loan_accounts",
            passed=orphan_loan == 0,
            detail=f"{orphan_loan} payment(s) with no matching loan account",
            expected="0",
            actual=str(orphan_loan),
        ))
    except Exception as e:
        report.add(CheckResult(
            category="Referential Integrity",
            check_name="payments_loan_fk",
            table="payments -> loan_accounts",
            passed=False,
            detail=f"Error: {e}",
        ))


# ---------------------------------------------------------------------------
# 4. Business Rule Validation
# ---------------------------------------------------------------------------

def check_business_rules(
    spark: SparkSession,
    report: QualityReport,
) -> None:
    """Validate domain-specific business rules."""

    try:
        loans = spark.table("loan_warehouse.loan_accounts")

        # Rule 1: Active loans must have current_balance > 0
        active_zero_balance = loans.filter(
            (F.col("status") == "ACTIVE") & (F.col("current_balance") <= 0)
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="active_loan_positive_balance",
            table="loan_accounts",
            passed=active_zero_balance == 0,
            detail=f"{active_zero_balance} active loan(s) with balance <= 0",
            expected="0",
            actual=str(active_zero_balance),
        ))

        # Rule 2: Closed loans should have a maturity_date <= origination_date is invalid
        # (maturity must be after origination for all loans)
        bad_dates = loans.filter(
            F.col("maturity_date") <= F.col("origination_date")
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="maturity_after_origination",
            table="loan_accounts",
            passed=bad_dates == 0,
            detail=f"{bad_dates} loan(s) where maturity_date <= origination_date",
            expected="0",
            actual=str(bad_dates),
        ))

        # Rule 3: Interest rate should be between 0 and 100
        bad_rates = loans.filter(
            (F.col("interest_rate") < 0) | (F.col("interest_rate") > 100)
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="interest_rate_range",
            table="loan_accounts",
            passed=bad_rates == 0,
            detail=f"{bad_rates} loan(s) with interest rate outside 0-100%",
            expected="0",
            actual=str(bad_rates),
        ))

        # Rule 4: LTV percent should be between 0 and 200 (if present)
        bad_ltv = loans.filter(
            F.col("ltv_percent").isNotNull() &
            ((F.col("ltv_percent") < 0) | (F.col("ltv_percent") > 200))
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="ltv_percent_range",
            table="loan_accounts",
            passed=bad_ltv == 0,
            detail=f"{bad_ltv} loan(s) with LTV outside 0-200%",
            expected="0",
            actual=str(bad_ltv),
        ))

        # Rule 5: Delinquency days >= 0
        bad_dlq = loans.filter(F.col("delinquency_days") < 0).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="delinquency_non_negative",
            table="loan_accounts",
            passed=bad_dlq == 0,
            detail=f"{bad_dlq} loan(s) with negative delinquency days",
            expected="0",
            actual=str(bad_dlq),
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rules",
            check_name="loan_business_rules",
            table="loan_accounts",
            passed=False,
            detail=f"Error: {e}",
        ))

    # Payment business rules
    try:
        payments = spark.table("loan_warehouse.payments")

        # Rule 6: Payment total_amount > 0 for POSTED payments
        bad_amounts = payments.filter(
            (F.col("status") == "POSTED") & (F.col("total_amount") <= 0)
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="posted_payment_positive_amount",
            table="payments",
            passed=bad_amounts == 0,
            detail=f"{bad_amounts} posted payment(s) with amount <= 0",
            expected="0",
            actual=str(bad_amounts),
        ))

        # Rule 7: Payment component sum should approximate total
        # (principal + interest + escrow + late_fee ≈ total_amount)
        component_check = payments.filter(
            F.col("status") == "POSTED"
        ).withColumn(
            "_component_sum",
            F.coalesce(F.col("principal_amount"), F.lit(0)) +
            F.coalesce(F.col("interest_amount"), F.lit(0)) +
            F.coalesce(F.col("escrow_amount"), F.lit(0)) +
            F.coalesce(F.col("late_fee"), F.lit(0))
        ).withColumn(
            "_diff", F.abs(F.col("total_amount") - F.col("_component_sum"))
        )
        mismatched = component_check.filter(F.col("_diff") > 0.02).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="payment_component_sum",
            table="payments",
            passed=mismatched == 0,
            detail=f"{mismatched} payment(s) where components don't sum to total (tolerance $0.02)",
            expected="0",
            actual=str(mismatched),
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rules",
            check_name="payment_business_rules",
            table="payments",
            passed=False,
            detail=f"Error: {e}",
        ))

    # Borrower business rules
    try:
        borrowers = spark.table("loan_warehouse.borrowers")

        # Rule 8: Credit score should be between 300 and 850 (if present)
        bad_credit = borrowers.filter(
            F.col("credit_score").isNotNull() &
            ((F.col("credit_score") < 300) | (F.col("credit_score") > 850))
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="credit_score_range",
            table="borrowers",
            passed=bad_credit == 0,
            detail=f"{bad_credit} borrower(s) with credit score outside 300-850",
            expected="0",
            actual=str(bad_credit),
        ))

        # Rule 9: Annual income should be non-negative (if present)
        bad_income = borrowers.filter(
            F.col("annual_income").isNotNull() & (F.col("annual_income") < 0)
        ).count()
        report.add(CheckResult(
            category="Business Rules",
            check_name="annual_income_non_negative",
            table="borrowers",
            passed=bad_income == 0,
            detail=f"{bad_income} borrower(s) with negative annual income",
            expected="0",
            actual=str(bad_income),
        ))

    except Exception as e:
        report.add(CheckResult(
            category="Business Rules",
            check_name="borrower_business_rules",
            table="borrowers",
            passed=False,
            detail=f"Error: {e}",
        ))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_all_checks(
    spark: SparkSession,
    source_counts: dict,
    report_path: str = "dbfs:/mnt/reports/data_quality/",
) -> QualityReport:
    """
    Execute all data quality checks and generate the report.

    Parameters:
        spark          : Active SparkSession
        source_counts  : Dict of expected row counts per table
        report_path    : DBFS path to write the markdown report

    Returns:
        QualityReport with all check results
    """
    report = QualityReport()

    print("=" * 70)
    print("Data Quality Validation")
    print(f"Started: {report.generated_at}")
    print("=" * 70)

    print("\n--- Row Count Reconciliation ---")
    check_row_counts(spark, report, source_counts)

    print("\n--- Null Checks ---")
    check_nulls(spark, report)

    print("\n--- Referential Integrity ---")
    check_referential_integrity(spark, report)

    print("\n--- Business Rules ---")
    check_business_rules(spark, report)

    # Generate markdown report
    print(f"\n--- Writing report to {report_path} ---")
    markdown_content = report.write_markdown(report_path, spark)

    print(f"\nOverall: {'PASS' if report.all_passed else 'FAIL'} "
          f"({report.passed_count}/{report.total_count} checks passed)")

    return report
