-- =============================================================================
-- Delta Lake Table: borrowers
-- =============================================================================
-- Source: CDW_BORR_MSTR (legacy all-VARCHAR borrower master table)
-- Target: borrowers (modern typed, normalized borrower dimension)
--
-- Key transformations from legacy:
--   - BORR_DOB_DT (VARCHAR MM/DD/YYYY) → date_of_birth (DATE)
--   - BORR_ANN_INCM (VARCHAR with commas) → annual_income (DECIMAL)
--   - BORR_CRDT_SCR (VARCHAR) → credit_score (INT)
--   - BORR_STAT_CD (abbreviation) → status (expanded string)
--   - BORR_REC_TYP dropped (not needed in modern schema)
--
-- Partitioning: by status — most queries filter by active/inactive borrowers
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_warehouse.borrowers (
    -- Surrogate key generated by Databricks (monotonically_increasing_id or identity)
    borrower_id         BIGINT          GENERATED ALWAYS AS IDENTITY,

    -- Natural key carried from legacy CDW_BORR_MSTR.BORR_ID
    external_id         STRING          NOT NULL,

    -- Borrower name fields (direct copy from legacy)
    first_name          STRING          NOT NULL,
    last_name           STRING          NOT NULL,
    middle_initial      STRING,

    -- SSN hash — carried over; re-encryption recommended post-migration
    ssn_hash            STRING,

    -- Date of birth — parsed from legacy MM/DD/YYYY VARCHAR
    date_of_birth       DATE,

    -- Address fields (direct copy from legacy)
    address_line1       STRING,
    address_line2       STRING,
    city                STRING,
    state               STRING,
    zip_code            STRING,

    -- Contact fields (direct copy from legacy)
    phone               STRING,
    email               STRING,

    -- Credit score — parsed from legacy VARCHAR to integer
    credit_score        INT,

    -- Employment status (direct copy from legacy)
    employment_status   STRING,

    -- Annual income — parsed from legacy comma-formatted VARCHAR to decimal
    annual_income       DECIMAL(12, 2),

    -- Status — expanded from legacy abbreviation (ACT→Active, INA→Inactive)
    status              STRING          NOT NULL DEFAULT 'Active',

    -- Audit timestamps — parsed from legacy MM/DD/YYYY strings
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,

    -- ETL metadata columns for lineage tracking
    _etl_loaded_at      TIMESTAMP       DEFAULT current_timestamp(),
    _etl_source         STRING          DEFAULT 'CDW_BORR_MSTR'
)
USING DELTA
-- Partition by status: most queries filter on active borrowers
PARTITIONED BY (status)
COMMENT 'Modern borrower dimension table migrated from legacy CDW_BORR_MSTR. All VARCHAR columns converted to proper types.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.columnMapping.mode' = 'name'
);

-- Unique constraint on external_id for dedup during ingestion
ALTER TABLE loan_warehouse.borrowers
    ADD CONSTRAINT borrowers_external_id_unique UNIQUE (external_id);
