-- =============================================================================
-- Delta Lake Table: borrowers
-- Source: CDW_BORR_MSTR (Legacy Borrower Master)
-- =============================================================================
-- Normalised borrower dimension split from the denormalized legacy loan table.
-- All VARCHAR date/amount columns are converted to proper Spark SQL types.
-- The BORR_REC_TYP column is intentionally dropped (not needed in modern schema).
-- Status codes are expanded: ACT → ACTIVE, INA → INACTIVE.
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_warehouse.borrowers (
    -- Surrogate key generated by Delta Lake (auto-increment via GENERATED ALWAYS)
    id                BIGINT       GENERATED ALWAYS AS IDENTITY,

    -- Legacy borrower identifier preserved for traceability
    external_id       STRING       NOT NULL  COMMENT 'Legacy BORR_ID from CDW_BORR_MSTR',

    -- Personal information
    first_name        STRING       NOT NULL  COMMENT 'Mapped from BORR_FST_NM',
    last_name         STRING       NOT NULL  COMMENT 'Mapped from BORR_LST_NM',
    middle_initial    STRING                 COMMENT 'Mapped from BORR_MID_INIT',
    ssn_hash          STRING                 COMMENT 'Mapped from BORR_SSN_ENCR — re-encryption recommended',
    date_of_birth     DATE                   COMMENT 'Parsed from BORR_DOB_DT (MM/DD/YYYY)',

    -- Contact & address
    address_line1     STRING                 COMMENT 'Mapped from BORR_ADDR_LN1',
    address_line2     STRING                 COMMENT 'Mapped from BORR_ADDR_LN2',
    city              STRING                 COMMENT 'Mapped from BORR_CTY_NM',
    state             STRING                 COMMENT 'Mapped from BORR_ST_CD (2-char)',
    zip_code          STRING                 COMMENT 'Mapped from BORR_ZIP_CD',
    phone             STRING                 COMMENT 'Mapped from BORR_PH_NBR',
    email             STRING                 COMMENT 'Mapped from BORR_EMAIL_ADDR',

    -- Financial profile
    credit_score      INT                    COMMENT 'Parsed from BORR_CRDT_SCR string → integer',
    employment_status STRING                 COMMENT 'Mapped from BORR_EMP_STAT',
    annual_income     DECIMAL(12,2)          COMMENT 'Parsed from BORR_ANN_INCM (commas removed)',

    -- Status
    status            STRING       NOT NULL  COMMENT 'Expanded from BORR_STAT_CD: ACT→ACTIVE, INA→INACTIVE',

    -- Audit timestamps
    created_at        TIMESTAMP              COMMENT 'Parsed from BORR_CRET_DT (MM/DD/YYYY)',
    updated_at        TIMESTAMP              COMMENT 'Parsed from BORR_UPDT_DT (MM/DD/YYYY)',

    -- Delta Lake metadata columns for CDC tracking
    _ingestion_ts     TIMESTAMP    DEFAULT current_timestamp() COMMENT 'Row ingestion timestamp',
    _source_system    STRING       DEFAULT 'CDW_BORR_MSTR'     COMMENT 'Source system identifier'
)
USING DELTA
COMMENT 'Borrower dimension table — migrated from legacy CDW_BORR_MSTR'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);

-- Unique constraint on legacy external_id to prevent duplicate imports
ALTER TABLE loan_warehouse.borrowers
    ADD CONSTRAINT borrowers_external_id_unique UNIQUE (external_id);
