-- =============================================================================
-- Delta Lake Table: borrowers
-- Source: CDW_BORR_MSTR (legacy all-VARCHAR borrower master table)
-- =============================================================================
-- Normalized borrower dimension extracted from the legacy CDW_BORR_MSTR table.
-- All VARCHAR columns are converted to proper Spark SQL types (DATE, INTEGER,
-- DECIMAL). The BORR_REC_TYP column is intentionally dropped as it carries no
-- business value in the modern schema.
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_warehouse.borrowers (
    -- Surrogate key generated by the ingestion pipeline
    id                  BIGINT          GENERATED ALWAYS AS IDENTITY,

    -- Legacy CDW_BORR_MSTR.BORR_ID preserved for lineage and back-reference
    external_id         STRING          NOT NULL    COMMENT 'Legacy BORR_ID from CDW_BORR_MSTR',

    -- Personal information
    first_name          STRING          NOT NULL    COMMENT 'Borrower first name (BORR_FST_NM)',
    last_name           STRING          NOT NULL    COMMENT 'Borrower last name (BORR_LST_NM)',
    middle_initial      STRING                      COMMENT 'Middle initial (BORR_MID_INIT)',
    ssn_hash            STRING          NOT NULL    COMMENT 'Encrypted SSN carried forward; re-encryption recommended (BORR_SSN_ENCR)',
    date_of_birth       DATE            NOT NULL    COMMENT 'Parsed from MM/DD/YYYY string (BORR_DOB_DT)',

    -- Address
    address_line1       STRING                      COMMENT 'BORR_ADDR_LN1',
    address_line2       STRING                      COMMENT 'BORR_ADDR_LN2 (nullable)',
    city                STRING                      COMMENT 'BORR_CTY_NM',
    state               STRING                      COMMENT 'Two-letter state code (BORR_ST_CD)',
    zip_code            STRING                      COMMENT 'BORR_ZIP_CD',

    -- Contact
    phone               STRING                      COMMENT 'BORR_PH_NBR',
    email               STRING                      COMMENT 'BORR_EMAIL_ADDR',

    -- Financial profile
    credit_score        INT             NOT NULL    COMMENT 'Parsed from VARCHAR; validated range 300-850 (BORR_CRDT_SCR)',
    employment_status   STRING                      COMMENT 'BORR_EMP_STAT (EMPLOYED, SELF-EMP, RETIRED, etc.)',
    annual_income       DECIMAL(12,2)   NOT NULL    COMMENT 'Parsed from comma-formatted string (BORR_ANN_INCM)',

    -- Audit timestamps (parsed from MM/DD/YYYY to full TIMESTAMP)
    created_at          TIMESTAMP       NOT NULL    COMMENT 'BORR_CRET_DT parsed to timestamp',
    updated_at          TIMESTAMP       NOT NULL    COMMENT 'BORR_UPDT_DT parsed to timestamp',

    -- Status (expanded from abbreviation: ACT -> ACTIVE, INA -> INACTIVE)
    status              STRING          NOT NULL    COMMENT 'Expanded status code (BORR_STAT_CD)',

    -- Ingestion metadata
    _legacy_source      STRING          DEFAULT 'CDW_BORR_MSTR'  COMMENT 'Source table for lineage',
    _ingested_at        TIMESTAMP       DEFAULT current_timestamp() COMMENT 'Pipeline ingestion timestamp'
)
USING DELTA
COMMENT 'Modern borrower dimension table migrated from legacy CDW_BORR_MSTR. All VARCHARs converted to proper types.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
