-- =============================================================================
-- Delta Lake Table: loan_products
-- =============================================================================
-- Reference/dimension table for available loan product types.
-- Source: CDW_LN_PROD (legacy all-VARCHAR loan products)
-- Transformations applied during ingestion:
--   - PROD_TERM_MOS (VARCHAR) → term_months (INT)
--   - PROD_MIN_AMT / PROD_MAX_AMT (VARCHAR with commas) → min_amount / max_amount (DECIMAL)
--   - PROD_STAT_CD (ACT/INA) → is_active (BOOLEAN)
--   - PROD_EFF_DT / PROD_EXP_DT (VARCHAR MM/DD/YYYY) → effective_date / expiration_date (DATE)
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_management.loan_products (
    -- Surrogate key auto-generated by Delta Lake
    id                  BIGINT        GENERATED ALWAYS AS IDENTITY,
    -- Legacy PROD_CD preserved for lookup and traceability
    code                STRING        NOT NULL,
    name                STRING        NOT NULL,
    -- Product type code (FXD, ARM, FHA, VA)
    type                STRING        NOT NULL,
    term_months         INT           NOT NULL,
    -- Rate type: FIXED or VARIABLE
    rate_type           STRING        NOT NULL,
    min_amount          DECIMAL(12, 2),
    max_amount          DECIMAL(12, 2),
    -- Converted from legacy PROD_STAT_CD: ACT → true, INA → false
    is_active           BOOLEAN       DEFAULT true,
    effective_date      DATE,
    expiration_date     DATE,
    -- Audit column: tracks the ingestion batch that loaded this row
    _ingestion_ts       TIMESTAMP     DEFAULT current_timestamp()
)
USING DELTA
COMMENT 'Loan product reference table. Migrated from legacy CDW_LN_PROD.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
