-- =============================================================================
-- Delta Lake Table: payments
-- =============================================================================
-- Transaction fact table for loan payment history.
-- Source: CDW_PMT_HIST (legacy all-VARCHAR payment records)
-- Transformations applied during ingestion:
--   - LN_ACCT_NBR resolved to loan_accounts FK via account_number lookup
--   - All amount VARCHARs (commas stripped) → DECIMAL
--   - All date VARCHARs (MM/DD/YYYY) → DATE / TIMESTAMP
--   - PMT_TYP_CD expanded: REG→REGULAR, EXT→EXTRA, PRT→PARTIAL, PRE→PREPAYMENT
--   - PMT_STAT_CD expanded: PST→POSTED, REV→REVERSED, NSF→NSF, PND→PENDING
-- Partitioned by payment_year for efficient time-range queries on payment history.
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_management.payments (
    -- Surrogate key auto-generated by Delta Lake
    id                  BIGINT        GENERATED ALWAYS AS IDENTITY,
    -- Legacy PMT_SEQ_NBR preserved for traceability and reconciliation
    legacy_payment_id   STRING,
    -- FK to loan_accounts.account_number (resolved during ingestion)
    loan_account_number STRING        NOT NULL,
    payment_date        DATE          NOT NULL,
    total_amount        DECIMAL(10, 2) NOT NULL,
    principal_amount    DECIMAL(10, 2),
    interest_amount     DECIMAL(10, 2),
    escrow_amount       DECIMAL(10, 2),
    late_fee            DECIMAL(10, 2) DEFAULT 0,
    -- Expanded from legacy code: REG→REGULAR, EXT→EXTRA, PRT→PARTIAL, PRE→PREPAYMENT
    type                STRING        NOT NULL,
    -- Expanded from legacy code: PST→POSTED, REV→REVERSED, NSF→NSF, PND→PENDING
    status              STRING        NOT NULL,
    received_date       DATE,
    processed_date      DATE,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    -- Derived partition column: extracted year from payment_date for partitioning
    payment_year        INT,
    -- Audit column: tracks the ingestion batch that loaded this row
    _ingestion_ts       TIMESTAMP     DEFAULT current_timestamp()
)
USING DELTA
-- Partition by payment_year for efficient time-range queries
PARTITIONED BY (payment_year)
COMMENT 'Payment transaction fact table. Migrated from legacy CDW_PMT_HIST. Partitioned by payment year.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
