-- =============================================================================
-- Delta Lake Table: borrowers
-- =============================================================================
-- Modern normalized borrower dimension table.
-- Source: CDW_BORR_MSTR (legacy all-VARCHAR borrower master)
-- Transformations applied during ingestion:
--   - BORR_DOB_DT (VARCHAR MM/DD/YYYY) → date_of_birth (DATE)
--   - BORR_CRDT_SCR (VARCHAR) → credit_score (INT)
--   - BORR_ANN_INCM (VARCHAR with commas) → annual_income (DECIMAL)
--   - BORR_STAT_CD (ACT/INA) → status (ACTIVE/INACTIVE)
--   - BORR_CRET_DT / BORR_UPDT_DT (VARCHAR) → created_at / updated_at (TIMESTAMP)
--   - BORR_REC_TYP dropped (not needed in modern schema)
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_management.borrowers (
    -- Surrogate key auto-generated by Delta Lake
    id                  BIGINT        GENERATED ALWAYS AS IDENTITY,
    -- Legacy BORR_ID preserved for traceability
    external_id         STRING        NOT NULL,
    first_name          STRING        NOT NULL,
    last_name           STRING        NOT NULL,
    middle_initial      STRING,
    -- Encrypted SSN carried over; re-encryption recommended post-migration
    ssn_hash            STRING,
    date_of_birth       DATE,
    address_line1       STRING,
    address_line2       STRING,
    city                STRING,
    state               STRING,
    zip_code            STRING,
    phone               STRING,
    email               STRING,
    credit_score        INT,
    employment_status   STRING,
    annual_income       DECIMAL(12, 2),
    -- Expanded from legacy status code (ACT → ACTIVE, INA → INACTIVE)
    status              STRING        DEFAULT 'ACTIVE',
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    -- Audit column: tracks the ingestion batch that loaded this row
    _ingestion_ts       TIMESTAMP     DEFAULT current_timestamp()
)
USING DELTA
-- Comment explains table purpose and lineage
COMMENT 'Borrower dimension table. Migrated from legacy CDW_BORR_MSTR.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
