-- =============================================================================
-- Delta Lake Table: loan_accounts
-- =============================================================================
-- Core fact table for individual loan accounts.
-- Source: CDW_LN_ACCT (legacy denormalized, all-VARCHAR loan accounts)
-- Key normalizations during ingestion:
--   - Denormalized borrower fields (BORR_FST_NM, BORR_LST_NM, BORR_SSN_LST4) dropped;
--     replaced by FK reference to borrowers via external_id lookup
--   - PROD_CD resolved to loan_products FK via code lookup
--   - All amount VARCHARs (commas stripped) → DECIMAL
--   - All date VARCHARs (MM/DD/YYYY) → DATE
--   - LN_STAT_CD expanded: ACT→ACTIVE, CLO→CLOSED, DFT→DEFAULT, FRB→FORBEARANCE
--   - PROP_TYP_CD expanded: SFR→Single Family, CND→Condominium, MFR→Multi-Family, TWN→Townhouse
-- Partitioned by status for efficient queries on active vs. closed loans.
-- =============================================================================

CREATE TABLE IF NOT EXISTS loan_management.loan_accounts (
    -- Surrogate key auto-generated by Delta Lake
    id                  BIGINT        GENERATED ALWAYS AS IDENTITY,
    -- Legacy LN_ACCT_NBR preserved for traceability
    account_number      STRING        NOT NULL,
    -- FK to borrowers.external_id (resolved during ingestion)
    borrower_external_id STRING       NOT NULL,
    -- FK to loan_products.code (resolved during ingestion)
    product_code        STRING        NOT NULL,
    original_amount     DECIMAL(12, 2) NOT NULL,
    current_balance     DECIMAL(12, 2) NOT NULL,
    interest_rate       DECIMAL(5, 3)  NOT NULL,
    term_months         INT            NOT NULL,
    monthly_payment     DECIMAL(10, 2) NOT NULL,
    origination_date    DATE           NOT NULL,
    maturity_date       DATE           NOT NULL,
    first_payment_date  DATE,
    next_payment_date   DATE,
    -- Expanded from legacy code: ACT→ACTIVE, CLO→CLOSED, DFT→DEFAULT, FRB→FORBEARANCE
    status              STRING         DEFAULT 'ACTIVE',
    delinquency_days    INT            DEFAULT 0,
    escrow_balance      DECIMAL(10, 2) DEFAULT 0,
    ltv_percent         DECIMAL(5, 2),
    property_address    STRING,
    property_city       STRING,
    property_state      STRING,
    property_zip        STRING,
    -- Expanded from legacy code: SFR→Single Family, CND→Condominium, etc.
    property_type       STRING,
    appraised_value     DECIMAL(12, 2),
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    -- Audit column: tracks the ingestion batch that loaded this row
    _ingestion_ts       TIMESTAMP      DEFAULT current_timestamp()
)
USING DELTA
-- Partition by status for efficient filtering on active/closed/default/forbearance loans
PARTITIONED BY (status)
COMMENT 'Loan account fact table. Migrated from legacy CDW_LN_ACCT. Partitioned by loan status.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
